apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-29T05:29:05Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "567"
  uid: a1c1cb73-d48d-4d15-ab46-47a8e0b7e12e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.7.156
  clusterIPs:
  - 10.108.7.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30550
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
